### ISSUE TITLE
Differential_coding-Compute e signal

### ISSUE THREAD

**Issue by vhar95** [vicente-gonzalez-ruiz/differential_coding#1]
Code to compute e signal of s signal and plot the probability density function
https://github.com/vicente-gonzalez-ruiz/differential_coding/blob/2d6dc4061df864ff64cf9bbed54e1f5c4afc0088/differential_coding.ipynb

**Comment by vicente-gonzalez-ruiz** [comment]
Thank you for closing it. I forget ...
